### ISSUE TITLE
Question about input data

### ISSUE THREAD

**Issue by k1ochiai** [weihua916/powerful-gnns#1]
Hi. Thanks for great work.
I have a question about input data, specifically for node id numbering.
Is a node id unique across all graphs? or unique in a graph?

I mean, graph 1 contains node A, B, C, and graph 2 contain node A, D, E.
Then, node ids for graph 1 and 2 are both node 1, 2, 3 (for inductive setting).
If transductive setting, node ids are 1, 2, 3 for graph1 and 1, 4, 5 for graph2.

Is it correct?

**Comment by weihua916** [comment]
Hi! Node ids are shared across graphs because we are considering graph classification.

**Comment by k1ochiai** [comment]
Thanks for your reply. I understand.
