### ISSUE TITLE
Inconsistent dataset description and actual data

### ISSUE THREAD

**Issue by mdanb** [weihua916/powerful-gnns#17]
Hi,
I'm looking at Table 1 in the paper, and the number of classes associated with the datasets does not match the description of the data in the appendix. For example, the MUTAG dataset has 2 classes according to the table (and the actual data labels that I checked, which are either 1 or -1), versus in the appendix it says that the dataset has 7 discrete labels. Was wondering if you could clarify the disagreement. 

Thank you!

**Comment by weihua916** [comment]
Hi! Thanks for your interest! The "7" means the number of categorical labels of the input node features.
